//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BridgeType
    {
        [Display(Name = "Id")]
        public int BridgeTypeId { get; set; }

        [Display(Name = "Bridge Type")]
        public string BridgeTypeName { get; set; }

        [Display(Name = "Short Code")]
        public string BridgeTypeShortCode { get; set; }

        [Display(Name = "Remark")]
        public string Remark { get; set; }
    }
}
