//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bridge
    {
        [Display(Name = "Id")]
        public string BridgeId { get; set; }

        [Display(Name = "Bridge")]
        public string BridgeName { get; set; }

        [Display(Name = "Ser. No.")]
        public Nullable<int> BridgeSerNo { get; set; }

        [Display(Name = "Segment")]
        public int SegmentId { get; set; }

        [Display(Name = "Route")]
        public string RouteId { get; set; }

        [Display(Name = "From Addis (Km)")]
        public Nullable<double> KMFromAddis { get; set; }

        [Display(Name = "X-Coord")]
        public Nullable<double> XCoord { get; set; }

        [Display(Name = "Y-Coord")]
        public Nullable<double> YCoord { get; set; }

        [Display(Name = "Girder Type")]
        public Nullable<short> GirderTypeId { get; set; }

        [Display(Name = "Budget Year")]
        public Nullable<int> BudgetYear { get; set; }

        [Display(Name = "Comment")]
        public Nullable<int> BudgetYearComment { get; set; }

        [Display(Name = "Girder Type")]
        public virtual GirderType GirderType { get; set; }

        public virtual Route Route { get; set; }

        public virtual Segment Segment { get; set; }
    }
}
