//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abutment
    {
        public string BridgeId { get; set; }
        public Nullable<int> AbutmentTypeIdA1 { get; set; }
        public Nullable<int> AbutmentTypeIdA2 { get; set; }
        public Nullable<double> AbutmentHeightA1 { get; set; }
        public Nullable<double> AbutmentHeightA2 { get; set; }
        public Nullable<double> AbutmentWidthA1 { get; set; }
        public Nullable<double> AbutmentWidthA2 { get; set; }
        public Nullable<double> WingWallLengthA1 { get; set; }
        public Nullable<double> WingWallLengthA2 { get; set; }
        public Nullable<int> FoundationTypeIdA1 { get; set; }
        public Nullable<int> FoundationTypeIdA2 { get; set; }
        public string FoundationSizeA1 { get; set; }
        public string FoundationSizeA2 { get; set; }
        public Nullable<int> NoOfAbutmentPilesA1 { get; set; }
        public Nullable<int> NoOfAbutmentPilesA2 { get; set; }
        public Nullable<double> AbutmentPileDepthA1 { get; set; }
        public Nullable<double> AbutmentPileDepthA2 { get; set; }
        public Nullable<int> SoilTypeA1 { get; set; }
        public Nullable<int> SoilTypeA2 { get; set; }
        public Nullable<int> NoOfpier { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual AbutmentType AbutmentType { get; set; }
        public virtual AbutmentType AbutmentType1 { get; set; }
        public virtual FoundationType FoundationType { get; set; }
        public virtual FoundationType FoundationType1 { get; set; }
        public virtual SoilType SoilType { get; set; }
        public virtual SoilType SoilType1 { get; set; }
        public virtual Bridge Bridge { get; set; }
    }
}
