//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ancillary
    {
        public string BridgeId { get; set; }
        public Nullable<int> ExpansionJointTypeId { get; set; }
        public Nullable<int> GuardRailingTypeId { get; set; }
        public Nullable<int> AbutmentBearingTypeId { get; set; }
        public Nullable<int> PiersBearingTypeId { get; set; }
        public Nullable<int> SurfaceTypeId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual BearingType BearingType { get; set; }
        public virtual ExpansionJointType ExpansionJointType { get; set; }
        public virtual GuardRailingType GuardRailingType { get; set; }
        public virtual BearingType BearingType1 { get; set; }
        public virtual SurfaceType SurfaceType { get; set; }
        public virtual Bridge Bridge { get; set; }
    }
}
