//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCMSEntities : DbContext
    {
        public BCMSEntities()
            : base("name=BCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbutmentType> AbutmentTypes { get; set; }
        public virtual DbSet<BearingType> BearingTypes { get; set; }
        public virtual DbSet<BridgeType> BridgeTypes { get; set; }
        public virtual DbSet<DeckSlabType> DeckSlabTypes { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<ExpansionJointType> ExpansionJointTypes { get; set; }
        public virtual DbSet<FoundationType> FoundationTypes { get; set; }
        public virtual DbSet<GuardRailingType> GuardRailingTypes { get; set; }
        public virtual DbSet<PierType> PierTypes { get; set; }
        public virtual DbSet<RoadAlignmentType> RoadAlignmentTypes { get; set; }
        public virtual DbSet<RoadType> RoadTypes { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<SpanSupportType> SpanSupportTypes { get; set; }
        public virtual DbSet<SurfaceType> SurfaceTypes { get; set; }
        public virtual DbSet<GirderType> GirderTypes { get; set; }
        public virtual DbSet<Bridge> Bridges { get; set; }
        public virtual DbSet<Culvert> Culverts { get; set; }
        public virtual DbSet<BridgeGeneralInfo> BridgeGeneralInfoes { get; set; }
        public virtual DbSet<SuperStructure> SuperStructures { get; set; }
        public virtual DbSet<Abutment> Abutments { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<BridgeDoc> BridgeDocs { get; set; }
        public virtual DbSet<BridgeHistory> BridgeHistories { get; set; }
        public virtual DbSet<Pier> Piers { get; set; }
        public virtual DbSet<ImageVideoDrawing> ImageVideoDrawings { get; set; }
    }
}
