//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeConditionByInspectionYear
    {
        public string BridgeId { get; set; }
        public string BridgeName { get; set; }
        public string SegmentId { get; set; }
        public string SectionId { get; set; }
        public string DistrictId { get; set; }
        public string BridgeTypeName { get; set; }
        public Nullable<double> BridgeLength { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public double DmgPerc2006 { get; set; }
        public int Bad2006 { get; set; }
        public int Fair2006 { get; set; }
        public int Good2006 { get; set; }
        public double DmgPerc2010 { get; set; }
        public int Bad2010 { get; set; }
        public int Fair2010 { get; set; }
        public int Good2010 { get; set; }
        public double DmgPerc2013 { get; set; }
        public int Bad2013 { get; set; }
        public int Fair2013 { get; set; }
        public int Good2013 { get; set; }
        public double DmgPerc2016 { get; set; }
        public int Bad2016 { get; set; }
        public int Fair2016 { get; set; }
        public int Good2016 { get; set; }
        public double DmgPerc2020 { get; set; }
        public int Bad2020 { get; set; }
        public int Fair2020 { get; set; }
        public int Good2020 { get; set; }
    }
}
