//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BridgeGeneralInfo
    {
        [Key, ForeignKey("Bridge")]
        public string BridgeGenInfoId { get; set; }
        public Nullable<double> BridgeLength { get; set; }
        public double TotBridgeLength { get; set; }
        public double BridgeWidth { get; set; }
        public double RiverWidth { get; set; }
        public Nullable<double> PresentWaterLevel { get; set; }
        public Nullable<double> HighestWaterLevel { get; set; }
        public Nullable<double> LoadCapacity { get; set; }
        public Nullable<int> DailyTraffic { get; set; }
        public string Topography { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<int> RoadAlignmentId { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public string BeforeYear { get; set; }
        public string Contractor { get; set; }
        public string Designer { get; set; }
        public Nullable<double> BridgeCost { get; set; }
        public bool SafetySign { get; set; }
        public bool Detour { get; set; }
    
        public virtual Bridge Bridge { get; set; }
        public virtual RoadAlignmentType RoadAlignmentType { get; set; }
    }
}
