//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgePriorityByHighestDamageRank
    {
        public string BridgeId { get; set; }
        public string RevisedBridgeNo { get; set; }
        public string BridgeName { get; set; }
        public string SegmentId { get; set; }
        public string SegmentName { get; set; }
        public string SectionId { get; set; }
        public string SectionName { get; set; }
        public string DistrictId { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> InspectionYear { get; set; }
        public Nullable<double> BridgeLength { get; set; }
        public string BridgeType { get; set; }
        public string Recommendation { get; set; }
        public string DeckSlab { get; set; }
        public string ConcreteGirder { get; set; }
        public string PierAndFoundation { get; set; }
        public string AbutmentAndWingWall { get; set; }
        public string Bearing { get; set; }
        public Nullable<double> RepairCost { get; set; }
    }
}
