//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bridge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bridge()
        {
            this.Piers = new HashSet<Pier>();
        }
    
        public string BridgeId { get; set; }
        public string BridgeName { get; set; }
        public Nullable<int> BridgeSerNo { get; set; }
        public int SegmentId { get; set; }
        public string RouteId { get; set; }
        public Nullable<double> KMFromAddis { get; set; }
        public Nullable<double> XCoord { get; set; }
        public Nullable<double> YCoord { get; set; }
        public Nullable<short> GirderTypeId { get; set; }
        public Nullable<int> BudgetYear { get; set; }
        public Nullable<int> BudgetYearComment { get; set; }
    
        public virtual GirderType GirderType { get; set; }
        public virtual Route Route { get; set; }
        public virtual Segment Segment { get; set; }
        public virtual BridgeGeneralInfo BridgeGeneralInfo { get; set; }
        public virtual SuperStructure SuperStructure { get; set; }
        public virtual Abutment Abutment { get; set; }
        public virtual BridgeDoc BridgeDoc { get; set; }
        public virtual BridgeHistory BridgeHistory { get; set; }
        public virtual Component Component { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pier> Piers { get; set; }
        public virtual ImageVideoDrawing ImageVideoDrawing { get; set; }
    }
}
