//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeDoc
    {
        public string Id { get; set; }
        public string BridgeId { get; set; }
        public Nullable<int> SerNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Description { get; set; }
        public string DocFilePath { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
        public int DocTypeId { get; set; }
    
        public virtual DocType DocType { get; set; }
        public virtual Bridge Bridge { get; set; }
    }
}
