//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeCurrentValue
    {
        public string BridgeId { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public Nullable<double> ConstructionCost { get; set; }
        public double ReplacementCost { get; set; }
        public Nullable<int> ServiceYears { get; set; }
        public Nullable<decimal> ServiceYearRate { get; set; }
        public Nullable<double> DOC { get; set; }
        public double TotalImprovementCost { get; set; }
        public Nullable<decimal> LatestPriorityVal { get; set; }
        public Nullable<decimal> BridgeConditionIndex { get; set; }
        public Nullable<double> DepreciatedReplacementCost { get; set; }
        public Nullable<double> CurrentValue { get; set; }
    }
}
