//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeRequiredActionByDistrict
    {
        public string District { get; set; }
        public int InspectionYear { get; set; }
        public int RegularInspection { get; set; }
        public int Rehabilitation { get; set; }
        public int Replacement { get; set; }
    }
}
