//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeTypeByDistrict
    {
        public string DistrictId { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> RC_Deck_Girder { get; set; }
        public Nullable<int> RC_Box_Girder { get; set; }
        public Nullable<int> RC_Arch { get; set; }
        public Nullable<int> RC_Slab_Bridge { get; set; }
        public Nullable<int> RC_Box_Culvert { get; set; }
        public Nullable<int> PC_Deck_Girder { get; set; }
        public Nullable<int> PC_Box_Girder { get; set; }
        public Nullable<int> Steel_Truss { get; set; }
        public Nullable<int> Steel_Girder_Composit { get; set; }
        public Nullable<int> Steel_Panel_Bailey { get; set; }
        public Nullable<int> Masonry_Arch { get; set; }
        public Nullable<int> Steel_Truss_and_RCDG { get; set; }
        public Nullable<int> RC_Box_Girder_and_RCDG { get; set; }
        public Nullable<int> RC_Arch_and_RCDG { get; set; }
        public Nullable<int> RC_Deck_Girder_and_RC_Slab { get; set; }
        public Nullable<int> RC_Rigid_Frame { get; set; }
        public Nullable<int> Extradosed_Cable { get; set; }
        public Nullable<int> Steel_Truss_and_Box_Girder { get; set; }
        public Nullable<int> Pipe_Steel_RC { get; set; }
        public Nullable<int> RC_Deck_Girder_Continuous { get; set; }
    }
}
