//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeCondition2013
    {
        public string BridgeId { get; set; }
        public Nullable<double> DamagePercent2013 { get; set; }
        public int Bad { get; set; }
        public int Fair { get; set; }
        public int Good { get; set; }
    }
}
