//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeGeneralInfo
    {
        public string BridgeId { get; set; }
        public Nullable<double> KMFromAddis { get; set; }
        public Nullable<double> XCoord { get; set; }
        public Nullable<double> YCoord { get; set; }
        public Nullable<double> BridgeLength { get; set; }
        public Nullable<double> BridgeWidth { get; set; }
        public Nullable<double> RiverWidth { get; set; }
        public Nullable<double> PresentWaterLevel { get; set; }
        public Nullable<double> HighestWaterLevel { get; set; }
        public Nullable<double> DesignCapacity { get; set; }
        public string Topography { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<int> RoadAlignmentId { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public Nullable<int> ReplacedYear { get; set; }
        public Nullable<bool> Before1935 { get; set; }
        public string Contractor { get; set; }
        public string Designer { get; set; }
        public Nullable<double> ConstructionCost { get; set; }
        public Nullable<double> AssetReplacementCost { get; set; }
        public Nullable<bool> SafetySign { get; set; }
        public Nullable<bool> DetourPossible { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
        public Nullable<int> UtmZoneId { get; set; }
        public Nullable<bool> BearingCapacity { get; set; }
    
        public virtual RoadAlignmentType RoadAlignmentType { get; set; }
        public virtual UtmZoneEthiopia UtmZoneEthiopia { get; set; }
        public virtual Bridge Bridge { get; set; }
    }
}
