//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BridgeHistory
    {
        [Key, ForeignKey("Bridge")]
        public string BridgeHistoryId { get; set; }
        public Nullable<short> LineNo { get; set; }
        public string HistoryDescr { get; set; }
    
        public virtual Bridge Bridge { get; set; }
    }
}
