//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeValuePerLm
    {
        public string DistrictName { get; set; }
        public Nullable<int> BridgeQuantity { get; set; }
        public Nullable<double> TotalBridgeLength { get; set; }
        public double BridgeAssetValue { get; set; }
        public Nullable<double> BridgeValuePerLM1 { get; set; }
    }
}
