//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentAndRemark
    {
        public int Id { get; set; }
        public string BridgeId { get; set; }
        public Nullable<int> InspectionYear { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<int> LineNo { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UrgencyId { get; set; }
        public Nullable<short> TRansCat { get; set; }
        public Nullable<bool> WaterWayAdequacy { get; set; }
    
        public virtual Bridge Bridge { get; set; }
        public virtual MaintenanceUrgency MaintenanceUrgency { get; set; }
    }
}
