//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class culDamageRateAndCost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public culDamageRateAndCost()
        {
            this.culDamageInspStructures = new HashSet<culDamageInspStructure>();
        }
    
        public int DamageTypeId { get; set; }
        public Nullable<int> Id { get; set; }
        public string DamageTypeName { get; set; }
        public Nullable<int> StructureItemId { get; set; }
        public string Unit { get; set; }
        public Nullable<double> DamageValue { get; set; }
        public Nullable<double> UnitRepairCost { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspStructure> culDamageInspStructures { get; set; }
        public virtual culStructureItem culStructureItem { get; set; }
    }
}
