//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class culDamageInspHydraulic
    {
        public string CulvertId { get; set; }
        public Nullable<int> OverTopping { get; set; }
        public Nullable<int> Constriction { get; set; }
        public Nullable<int> EmbankmentScour { get; set; }
        public Nullable<int> ChannelScour { get; set; }
        public Nullable<int> ChannelObstruction { get; set; }
        public Nullable<int> Siltation { get; set; }
        public Nullable<int> Vegitation { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual culHydrDamageType culHydrDamageType { get; set; }
        public virtual culHydrDamageType culHydrDamageType1 { get; set; }
        public virtual culHydrDamageType culHydrDamageType2 { get; set; }
        public virtual culHydrDamageType culHydrDamageType3 { get; set; }
        public virtual culHydrDamageType culHydrDamageType4 { get; set; }
        public virtual culHydrDamageType culHydrDamageType5 { get; set; }
        public virtual culHydrDamageType culHydrDamageType6 { get; set; }
        public virtual Culvert Culvert { get; set; }
    }
}
