//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class culDamageInspStructure
    {
        public string Id { get; set; }
        public string CulvertId { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public int StructureItemId { get; set; }
        public int DamageTypeId { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual culDamageRateAndCost culDamageRateAndCost { get; set; }
        public virtual Culvert Culvert { get; set; }
    }
}
