//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class culHydrDamageType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public culHydrDamageType()
        {
            this.culDamageInspHydraulics = new HashSet<culDamageInspHydraulic>();
            this.culDamageInspHydraulics1 = new HashSet<culDamageInspHydraulic>();
            this.culDamageInspHydraulics2 = new HashSet<culDamageInspHydraulic>();
            this.culDamageInspHydraulics3 = new HashSet<culDamageInspHydraulic>();
            this.culDamageInspHydraulics4 = new HashSet<culDamageInspHydraulic>();
            this.culDamageInspHydraulics5 = new HashSet<culDamageInspHydraulic>();
            this.culDamageInspHydraulics6 = new HashSet<culDamageInspHydraulic>();
        }
    
        public int DamageTypeId { get; set; }
        public string DamageTypeName { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspHydraulic> culDamageInspHydraulics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspHydraulic> culDamageInspHydraulics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspHydraulic> culDamageInspHydraulics2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspHydraulic> culDamageInspHydraulics3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspHydraulic> culDamageInspHydraulics4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspHydraulic> culDamageInspHydraulics5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspHydraulic> culDamageInspHydraulics6 { get; set; }
    }
}
