//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culvert
    {
        public string CulvertId { get; set; }
        public string CulvertName { get; set; }
        public Nullable<int> SegmentId { get; set; }
        public string RouteId { get; set; }
        public Nullable<double> KMFromAddis { get; set; }
        public Nullable<double> XCoord { get; set; }
        public Nullable<double> YCoord { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Segment Segment { get; set; }
    }
}
