//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CulvertValuePerLm
    {
        public string DistrictName { get; set; }
        public Nullable<int> CulvertQuantity { get; set; }
        public Nullable<double> TotalCulvertLength { get; set; }
        public double CulvertAssetValue { get; set; }
        public Nullable<double> CulvertValuePerLM1 { get; set; }
    }
}
