//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CulvertConditionIndex
    {
        public int CulvertConditionId { get; set; }
        public string CulvertConditionName { get; set; }
        public Nullable<double> ConditionIndex { get; set; }
        public string Remark { get; set; }
    
        public virtual MaintenanceUrgency MaintenanceUrgency { get; set; }
    }
}
