//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culvert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Culvert()
        {
            this.culDamageInspStructures = new HashSet<culDamageInspStructure>();
            this.CulvertMedias = new HashSet<CulvertMedia>();
            this.CulvertImprovements = new HashSet<CulvertImprovement>();
        }
    
        public string CulvertId { get; set; }
        public string CulvertNo { get; set; }
        public string RevisedCulvertNo { get; set; }
        public string SegmentId { get; set; }
        public string SubRouteId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual culDamageInspHydraulic culDamageInspHydraulic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<culDamageInspStructure> culDamageInspStructures { get; set; }
        public virtual Segment Segment { get; set; }
        public virtual SubRoute SubRoute { get; set; }
        public virtual CulvertGeneralInfo CulvertGeneralInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CulvertMedia> CulvertMedias { get; set; }
        public virtual CulvertStructure CulvertStructure { get; set; }
        public virtual ObservationAndRecommendation ObservationAndRecommendation { get; set; }
        public virtual ResultInspCulvert ResultInspCulvert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CulvertImprovement> CulvertImprovements { get; set; }
    }
}
