//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CulvertGeneralInfo
    {
        public string CulvertId { get; set; }
        public Nullable<double> KMFromAddis { get; set; }
        public Nullable<double> XCoord { get; set; }
        public Nullable<double> YCoord { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public string Designer { get; set; }
        public string Contractor { get; set; }
        public string Supervisor { get; set; }
        public Nullable<double> AssetReplacementCost { get; set; }
        public Nullable<bool> DetourPossible { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<double> RoadWidth { get; set; }
        public Nullable<double> HeadWallLength { get; set; }
        public Nullable<double> FillHeight { get; set; }
        public Nullable<int> ParapetMaterialTypeId { get; set; }
        public Nullable<double> ParapetLength { get; set; }
        public Nullable<int> NoOfLanes { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
        public Nullable<double> ConstructionCost { get; set; }
        public Nullable<int> UtmZoneId { get; set; }
    
        public virtual ParapetMaterialType ParapetMaterialType { get; set; }
        public virtual UtmZoneEthiopia UtmZoneEthiopia { get; set; }
        public virtual Culvert Culvert { get; set; }
    }
}
