//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CulvertStructure
    {
        public string CulvertId { get; set; }
        public Nullable<int> CulvertTypeId { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> LengthInside { get; set; }
        public Nullable<double> NoOfBarrels { get; set; }
        public Nullable<double> BarrelsDistance { get; set; }
        public Nullable<double> LengthTotal { get; set; }
        public Nullable<int> AbutmentTypeId { get; set; }
        public Nullable<double> AbutmentHeight { get; set; }
        public Nullable<int> EndWallTypeIdOut { get; set; }
        public Nullable<int> EndWallTypeIdIn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual AbutmentType AbutmentType { get; set; }
        public virtual culEndWallType culEndWallType { get; set; }
        public virtual culEndWallType culEndWallType1 { get; set; }
        public virtual CulvertType CulvertType { get; set; }
        public virtual Culvert Culvert { get; set; }
    }
}
