//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CulvertImprovement
    {
        public string Id { get; set; }
        public string CulvertId { get; set; }
        public Nullable<int> ImprovementYear { get; set; }
        public Nullable<System.DateTime> ImprovementDate { get; set; }
        public Nullable<int> ImprovementTypeId { get; set; }
        public string ImprovementAction { get; set; }
        public Nullable<double> ImprovementCost { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual Culvert Culvert { get; set; }
        public virtual ImprovementType ImprovementType { get; set; }
    }
}
