//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CulvertTypeBySegment
    {
        public string SegmentId { get; set; }
        public string SegmentName { get; set; }
        public string SectionId { get; set; }
        public string DistrictId { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Slab_Culvert { get; set; }
        public Nullable<int> Arch_Culvert { get; set; }
        public Nullable<int> Box_Culvert { get; set; }
        public Nullable<int> RC_Pipe { get; set; }
        public Nullable<int> Metal_Pipe { get; set; }
        public Nullable<int> Ford { get; set; }
        public Nullable<int> Mixed { get; set; }
        public Nullable<int> Not_Visible { get; set; }
    }
}
