//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamagePriority
    {
        public int Id { get; set; }
        public int PrioritizationCriteriaId { get; set; }
        public int CriteriaSerNo { get; set; }
        public int DmgValFrom { get; set; }
        public int DmgValTo { get; set; }
        public int DmgWtVal { get; set; }
        public Nullable<int> DmgItemGroupId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual DamagePrioritizationCriteria DamagePrioritizationCriteria { get; set; }
    }
}
