//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DamageType()
        {
            this.DamageInspVisuals = new HashSet<DamageInspVisual>();
            this.DamageInspMajors = new HashSet<DamageInspMajor>();
            this.DamageRateAndCosts = new HashSet<DamageRateAndCost>();
        }
    
        public int Id { get; set; }
        public int DamageTypeId { get; set; }
        public string DamageTypeName { get; set; }
        public int StructureItemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageInspVisual> DamageInspVisuals { get; set; }
        public virtual StructureItem StructureItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageInspMajor> DamageInspMajors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageRateAndCost> DamageRateAndCosts { get; set; }
    }
}
