//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageRateAndCost
    {
        public int Id { get; set; }
        public int DamageTypeId { get; set; }
        public int StructureItemId { get; set; }
        public string Unit { get; set; }
        public Nullable<short> DamageRankId { get; set; }
        public Nullable<double> DamagePercentValue { get; set; }
        public Nullable<double> UnitRepairCost { get; set; }
        public string Description { get; set; }
        public Nullable<short> RankNo { get; set; }
        public string DamagePictureFileName { get; set; }
        public Nullable<short> IsSelected { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual DamageRank DamageRank { get; set; }
        public virtual DamageType DamageType { get; set; }
    }
}
