//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageInspMajor
    {
        public string Id { get; set; }
        public string BridgeId { get; set; }
        public Nullable<int> StructureItemId { get; set; }
        public Nullable<int> DamageTypeId { get; set; }
        public Nullable<int> InspectionYear { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<short> DamageRankId { get; set; }
        public Nullable<double> DamageArea { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual DamageRank DamageRank { get; set; }
        public virtual DamageType DamageType { get; set; }
        public virtual Bridge Bridge { get; set; }
    }
}
