//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMSEntities : DbContext
    {
        public BMSEntities()
            : base("name=BMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BridgeCondition2016> BridgeCondition2016 { get; set; }
        public virtual DbSet<Abutment> Abutments { get; set; }
        public virtual DbSet<AbutmentType> AbutmentTypes { get; set; }
        public virtual DbSet<Ancillary> Ancillaries { get; set; }
        public virtual DbSet<BearingType> BearingTypes { get; set; }
        public virtual DbSet<BridgeComment> BridgeComments { get; set; }
        public virtual DbSet<BridgeMedia> BridgeMedias { get; set; }
        public virtual DbSet<BridgeObservation> BridgeObservations { get; set; }
        public virtual DbSet<BridgePart> BridgeParts { get; set; }
        public virtual DbSet<BridgePartDmgWt> BridgePartDmgWts { get; set; }
        public virtual DbSet<BridgeType> BridgeTypes { get; set; }
        public virtual DbSet<ConstructionYear> ConstructionYears { get; set; }
        public virtual DbSet<culDamageInspHydraulic> culDamageInspHydraulics { get; set; }
        public virtual DbSet<culDamageInspStructure> culDamageInspStructures { get; set; }
        public virtual DbSet<culDamageRateAndCost> culDamageRateAndCosts { get; set; }
        public virtual DbSet<culEndWallType> culEndWallTypes { get; set; }
        public virtual DbSet<culHydrDamageType> culHydrDamageTypes { get; set; }
        public virtual DbSet<culStructureItem> culStructureItems { get; set; }
        public virtual DbSet<CulvertMedia> CulvertMedias { get; set; }
        public virtual DbSet<CulvertStructure> CulvertStructures { get; set; }
        public virtual DbSet<CulvertType> CulvertTypes { get; set; }
        public virtual DbSet<DamageConditionRange> DamageConditionRanges { get; set; }
        public virtual DbSet<DamageInspVisual> DamageInspVisuals { get; set; }
        public virtual DbSet<DamageRank> DamageRanks { get; set; }
        public virtual DbSet<DamageSeverity> DamageSeverities { get; set; }
        public virtual DbSet<DamageType> DamageTypes { get; set; }
        public virtual DbSet<DeckSlabType> DeckSlabTypes { get; set; }
        public virtual DbSet<ExpansionJointType> ExpansionJointTypes { get; set; }
        public virtual DbSet<FoundationType> FoundationTypes { get; set; }
        public virtual DbSet<GirderType> GirderTypes { get; set; }
        public virtual DbSet<GuardRailingType> GuardRailingTypes { get; set; }
        public virtual DbSet<ImprovementType> ImprovementTypes { get; set; }
        public virtual DbSet<MainRoute> MainRoutes { get; set; }
        public virtual DbSet<MaintenanceUrgency> MaintenanceUrgencies { get; set; }
        public virtual DbSet<MajorInspectionYear> MajorInspectionYears { get; set; }
        public virtual DbSet<MediaType> MediaTypes { get; set; }
        public virtual DbSet<ObservationAndRecommendation> ObservationAndRecommendations { get; set; }
        public virtual DbSet<ParapetMaterialType> ParapetMaterialTypes { get; set; }
        public virtual DbSet<Pier> Piers { get; set; }
        public virtual DbSet<PierType> PierTypes { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<RequiredAction> RequiredActions { get; set; }
        public virtual DbSet<ResultInspCulvert> ResultInspCulverts { get; set; }
        public virtual DbSet<RoadAlignmentType> RoadAlignmentTypes { get; set; }
        public virtual DbSet<RoadClass> RoadClasses { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SoilType> SoilTypes { get; set; }
        public virtual DbSet<SpanSupportType> SpanSupportTypes { get; set; }
        public virtual DbSet<StructureItem> StructureItems { get; set; }
        public virtual DbSet<StructureItemDmgWt> StructureItemDmgWts { get; set; }
        public virtual DbSet<SubRoute> SubRoutes { get; set; }
        public virtual DbSet<SuperStructure> SuperStructures { get; set; }
        public virtual DbSet<SurfaceType> SurfaceTypes { get; set; }
        public virtual DbSet<BridgeCondition2006> BridgeCondition2006 { get; set; }
        public virtual DbSet<BridgeCondition2010> BridgeCondition2010 { get; set; }
        public virtual DbSet<BridgeCondition2013> BridgeCondition2013 { get; set; }
        public virtual DbSet<BridgeCondition2017> BridgeCondition2017 { get; set; }
        public virtual DbSet<BridgeCondition2020> BridgeCondition2020 { get; set; }
        public virtual DbSet<BridgeConditionAndRepairCostByDistrict> BridgeConditionAndRepairCostByDistricts { get; set; }
        public virtual DbSet<BridgeLengthByDistrict> BridgeLengthByDistricts { get; set; }
        public virtual DbSet<BridgeValuePerLm> BridgeValuePerLms { get; set; }
        public virtual DbSet<CulvertConditionAndRepairCostByDistrict> CulvertConditionAndRepairCostByDistricts { get; set; }
        public virtual DbSet<CulvertLengthByDistrict> CulvertLengthByDistricts { get; set; }
        public virtual DbSet<CulvertValuePerLm> CulvertValuePerLms { get; set; }
        public virtual DbSet<InvalidCulvertInspectionDate> InvalidCulvertInspectionDates { get; set; }
        public virtual DbSet<NoOfBridgesByDistrict> NoOfBridgesByDistricts { get; set; }
        public virtual DbSet<CulvertTypeByDistrict> CulvertTypeByDistricts { get; set; }
        public virtual DbSet<CulvertTypeBySection> CulvertTypeBySections { get; set; }
        public virtual DbSet<BridgeConditionAndRepairCostBySection> BridgeConditionAndRepairCostBySections { get; set; }
        public virtual DbSet<BridgeConditionAndRepairCostBySegment> BridgeConditionAndRepairCostBySegments { get; set; }
        public virtual DbSet<BridgeConditionByInspectionYear> BridgeConditionByInspectionYears { get; set; }
        public virtual DbSet<CulvertConditionAndRepairCostBySection> CulvertConditionAndRepairCostBySections { get; set; }
        public virtual DbSet<CulvertConditionAndRepairCostBySegment> CulvertConditionAndRepairCostBySegments { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<DamageInspMajor> DamageInspMajors { get; set; }
        public virtual DbSet<ResultInspMajor> ResultInspMajors { get; set; }
        public virtual DbSet<CulvertGeneralInfo> CulvertGeneralInfoes { get; set; }
        public virtual DbSet<UtmZoneEthiopia> UtmZoneEthiopias { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DamagePrioritizationCriteria> DamagePrioritizationCriterias { get; set; }
        public virtual DbSet<DamagePriority> DamagePriorities { get; set; }
        public virtual DbSet<DamagePriorityCriteriaAndSum> DamagePriorityCriteriaAndSums { get; set; }
        public virtual DbSet<BridgeLength> BridgeLengths { get; set; }
        public virtual DbSet<BridgeRequiredActionByDistrict> BridgeRequiredActionByDistricts { get; set; }
        public virtual DbSet<AssetValueByDistrict> AssetValueByDistricts { get; set; }
        public virtual DbSet<RepairCostAndRecommendation> RepairCostAndRecommendations { get; set; }
        public virtual DbSet<BridgeTypeByDistrict> BridgeTypeByDistricts { get; set; }
        public virtual DbSet<BridgeTypeByMainRoute> BridgeTypeByMainRoutes { get; set; }
        public virtual DbSet<BridgeTypeBySection> BridgeTypeBySections { get; set; }
        public virtual DbSet<BridgeTypeBySegment> BridgeTypeBySegments { get; set; }
        public virtual DbSet<CulvertTypeBySegment> CulvertTypeBySegments { get; set; }
        public virtual DbSet<BridgeGeneralInfo> BridgeGeneralInfoes { get; set; }
        public virtual DbSet<BridgeDoc> BridgeDocs { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<SegmentMap> SegmentMaps { get; set; }
        public virtual DbSet<DistrictMap> DistrictMaps { get; set; }
        public virtual DbSet<SectionMap> SectionMaps { get; set; }
        public virtual DbSet<DesignStandard> DesignStandards { get; set; }
        public virtual DbSet<RegionalGovernment> RegionalGovernments { get; set; }
        public virtual DbSet<RoadSurfaceType> RoadSurfaceTypes { get; set; }
        public virtual DbSet<BridgeCurrentValue> BridgeCurrentValues { get; set; }
        public virtual DbSet<CulvertConditionIndex> CulvertConditionIndexes { get; set; }
        public virtual DbSet<CulvertCurrentValue> CulvertCurrentValues { get; set; }
        public virtual DbSet<Bridge> Bridges { get; set; }
        public virtual DbSet<Culvert> Culverts { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<BridgePriorityByHighestDamageRank> BridgePriorityByHighestDamageRanks { get; set; }
        public virtual DbSet<BridgePriorityByInterventionRequirement> BridgePriorityByInterventionRequirements { get; set; }
        public virtual DbSet<PriorityParameter> PriorityParameters { get; set; }
        public virtual DbSet<CulvertsForUpgrading> CulvertsForUpgradings { get; set; }
        public virtual DbSet<BridgeTypeByRegion> BridgeTypeByRegions { get; set; }
        public virtual DbSet<CulvertTypeByRegion> CulvertTypeByRegions { get; set; }
        public virtual DbSet<DamageRateAndCost> DamageRateAndCosts { get; set; }
        public virtual DbSet<BridgeImprovement> BridgeImprovements { get; set; }
        public virtual DbSet<CulvertImprovement> CulvertImprovements { get; set; }
    }
}
