//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ImageVideoDrawing
    {
        [Key, ForeignKey("Bridge")]
        public string BridgeImageId { get; set; }
        public Nullable<int> BudgetYear { get; set; }
        public Nullable<short> PictureType { get; set; }
        public Nullable<int> PictureId { get; set; }
        public string PicDate { get; set; }
        public string PicDescr { get; set; }
        public string PicFileName { get; set; }
    
        public virtual Bridge Bridge { get; set; }
    }
}
