//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvalidCulvertInspectionDate
    {
        public string CulvertId { get; set; }
        public string SegmentName { get; set; }
        public string SectionName { get; set; }
        public string DistrictName { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<double> DamagePerc { get; set; }
        public Nullable<double> RepairCost { get; set; }
    }
}
