//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorInspectionYear
    {
        public int Id { get; set; }
        public int InspectionYear { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<int> NoOfRegisteredBridges { get; set; }
        public Nullable<int> NoOfRegisteredCulverts { get; set; }
        public Nullable<int> NoOfInspectedBridges { get; set; }
        public Nullable<int> NofInspectedCulverts { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    }
}
