//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pier
    {
        public string Id { get; set; }
        public string BridgeId { get; set; }
        public int PierNo { get; set; }
        public Nullable<int> PierTypeId { get; set; }
        public Nullable<double> HeightOfPier { get; set; }
        public Nullable<double> WidthOfPier { get; set; }
        public Nullable<int> FoundationTypeId { get; set; }
        public string FoundationDimension { get; set; }
        public Nullable<int> NoOfPierPiles { get; set; }
        public Nullable<double> PierPileDepth { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual FoundationType FoundationType { get; set; }
        public virtual PierType PierType { get; set; }
        public virtual Bridge Bridge { get; set; }
    }
}
