//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityParameter
    {
        public string BridgeId { get; set; }
        public string RevisedBridgeNo { get; set; }
        public string BridgeName { get; set; }
        public string DistrictId { get; set; }
        public string DistrictName { get; set; }
        public string SectionId { get; set; }
        public string SectionName { get; set; }
        public string SegmentId { get; set; }
        public string SegmentName { get; set; }
        public Nullable<int> InspectionYear { get; set; }
        public Nullable<double> DmgPerc { get; set; }
        public int UrgencyId { get; set; }
        public string UrgencyName { get; set; }
        public bool WaterWayAdequacy { get; set; }
        public Nullable<int> RoadClassId { get; set; }
        public string RoadClassName { get; set; }
        public Nullable<double> BridgeLength { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public Nullable<bool> DetourPossible { get; set; }
        public double ADT { get; set; }
        public Nullable<double> RepairCost { get; set; }
    }
}
