//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultInspMajor
    {
        public string BridgeId { get; set; }
        public int InspectionYear { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<double> DmgPercSubStructure { get; set; }
        public Nullable<double> DmgPercSuperStructure { get; set; }
        public Nullable<double> DmgPercAncillaries { get; set; }
        public Nullable<double> DmgPerc { get; set; }
        public Nullable<double> DmgPercAvg { get; set; }
        public Nullable<double> TotalDamageRatio { get; set; }
        public Nullable<double> RepairCostRatio { get; set; }
        public Nullable<double> RepairCostSubStruct { get; set; }
        public Nullable<double> RepairCostSuperStruct { get; set; }
        public Nullable<double> RepairCostAncillaries { get; set; }
        public Nullable<bool> WaterWayAdequacy_Insp { get; set; }
        public Nullable<int> RecomendationCode_Insp { get; set; }
        public string Recomendation_Insp { get; set; }
        public Nullable<short> RecStatus { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
        public string Id { get; set; }
    
        public virtual Bridge Bridge { get; set; }
    }
}
