//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionMap
    {
        public string SectionId { get; set; }
        public string MapFile { get; set; }
        public string MapFilePath { get; set; }
        public Nullable<System.DateTime> MapDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
