//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StructureItem()
        {
            this.DamageTypes = new HashSet<DamageType>();
        }
    
        public int StructureItemId { get; set; }
        public string StructureItemName { get; set; }
        public Nullable<short> BridgePartId { get; set; }
        public string Remark { get; set; }
    
        public virtual BridgePart BridgePart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageType> DamageTypes { get; set; }
        public virtual StructureItemDmgWt StructureItemDmgWt { get; set; }
    }
}
