//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubRoute()
        {
            this.Bridges = new HashSet<Bridge>();
            this.Culverts = new HashSet<Culvert>();
        }
    
        public string SubRouteId { get; set; }
        public string SubRouteNo { get; set; }
        public string SubRouteName { get; set; }
        public string MainRouteId { get; set; }
        public Nullable<double> FromKm { get; set; }
        public Nullable<double> ToKm { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> AverageDailyTraffic { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Flag { get; set; }
    
        public virtual MainRoute MainRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bridge> Bridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Culvert> Culverts { get; set; }
    }
}
