//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SuperStructure
    {
        [Key, ForeignKey("Bridge")]
        public string BridgeSuperStructureId { get; set; }
        public Nullable<int> BridgeTypeId { get; set; }
        public Nullable<int> NoOfSpan { get; set; }
        public string SpanLengthComposition { get; set; }
        public double TotalSpanLength { get; set; }
        public Nullable<double> CarriageWayWidth { get; set; }
        public Nullable<double> SideWalkWidth { get; set; }
        public Nullable<int> NoOfLane { get; set; }
        public Nullable<int> SpanSupportTypeId { get; set; }
        public Nullable<int> DeckSlabTypeId { get; set; }
        public Nullable<double> SlabThickness { get; set; }
        public Nullable<int> NoOfGirder { get; set; }
        public Nullable<double> GirderDepth { get; set; }
        public Nullable<double> SpacingGirder { get; set; }
        public Nullable<double> BoxWidth { get; set; }
    
        public virtual Bridge Bridge { get; set; }
        public virtual BridgeType BridgeType { get; set; }
        public virtual DeckSlabType DeckSlabType { get; set; }
        public virtual SpanSupportType SpanSupportType { get; set; }
    }
}
