//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA_BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtmZoneEthiopia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UtmZoneEthiopia()
        {
            this.CulvertGeneralInfoes = new HashSet<CulvertGeneralInfo>();
            this.BridgeGeneralInfoes = new HashSet<BridgeGeneralInfo>();
        }
    
        public int UtmZoneId { get; set; }
        public int UtmZone { get; set; }
        public string CentralMeridian { get; set; }
        public string Longitude { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CulvertGeneralInfo> CulvertGeneralInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BridgeGeneralInfo> BridgeGeneralInfoes { get; set; }
    }
}
